### ISSUE TITLE
"node server.js" results in "Error: Cannot add an empty service to a server"

### ISSUE THREAD

**Issue by jab** [googlecodelabs/cloud-grpc#7]
I'm going through this tutorial and have already hit #5 / #6 due to grpc being updated since the tutorial was written. Now I've hit the following issue:

When https://codelabs.developers.google.com/codelabs/cloud-grpc/index.html?index=..%2F..%2Findex#4 instructs you to run "node server.js" for the first time, it doesn't say you should get an error, but you do:
```
$ node server.js
/Users/<user>/src/cloud-grpc/start/node_modules/grpc/src/node/src/server.js:735
    throw new Error('Cannot add an empty service to a server');
    ^

Error: Cannot add an empty service to a server
    at Server.addService (/Users/<user>/src/cloud-grpc/start/node_modules/grpc/src/node/src/server.js:735:11)
    at Server.addProtoService (/Users/<user>/src/cloud-grpc/start/node_modules/grpc/src/node/src/server.js:786:8)
    at Object.<anonymous> (/Users/<user>/src/cloud-grpc/start/server.js:7:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
```

It looks like I can ignore this one and keep going through the tutorial, but thought I'd open this so you're aware of this issue too. I think I'll stop here though, and hopefully you can take care of any other updates that are required so users can get through the tutorial smoothly. Thanks!

/cc @MakMukhi

**Comment by Tuxdude** [comment]
+1 to this.

It would be great to fix the tutorial such that the initial version of books.proto defines at least one rpc in the service definition like this one:

```proto
syntax = "proto3";
package books;
service BookService {
  rpc List (Empty) returns (Empty) {}
}
message Empty {}
```

**Comment by thesandlord** [comment]
@Tuxdude thanks for the fix, we are updating this now! Will close once the new lab is published
